### ISSUE TITLE
没看懂该怎么设置  呜呜

### ISSUE THREAD

**Issue by 233333LSSSSSSSS** [Yann-zhou/zzu_auto_jksb#1]
没看懂该怎么设置  呜呜

**Comment by SoodaMoe** [comment]
那我去完善一下actions部分的教程，之前都是在用docker，就没有很用心写。
不过用docker的话会方便很多，如果有长时间开机的服务器的话直接拉取docker镜像就行了。

**Comment by SoodaMoe** [comment]
已经完善教程，还有不明白的地方还请继续提出~
