### ISSUE TITLE
大佬坚持住，打卡系统这两拨验证码更新，就剩你这根独苗了

### ISSUE THREAD

**Issue by LQY0606** [Yann-zhou/zzu_auto_jksb#2]

**Comment by SoodaMoe** [comment]
没这么夸张
而且说不定过两天再升级验证码之后我也放弃了……

**Comment by LQY0606** [comment]
> 没这么夸张 而且说不定过两天再升级验证码之后我也放弃了……

又失败了，验证码识别成功，提交打卡信息成功，最后却打卡失败。
![Screenshot_20220908_005026_com microsoft emmx](https://user-images.githubusercontent.com/91514324/188935821-33d94d87-32ca-4973-a9ec-816d071da077.png)

**Comment by Yann-zhou** [comment]
我这边没有问题。
你这边的情况应该是验证码识别错了，暂时无解。
验证码每个账号每天貌似是不变的，你可以把这个验证码的图片发一下我看看能不能提高识别精度。

**Comment by SoodaMoe** [comment]
> > 没这么夸张 而且说不定过两天再升级验证码之后我也放弃了……
> 
> 又失败了，验证码识别成功，提交打卡信息成功，最后却打卡失败。 ![Screenshot_20220908_005026_com microsoft emmx](https://user-images.githubusercontent.com/91514324/188935821-33d94d87-32ca-4973-a9ec-816d071da077.png)

我这边没有问题。
你这边的情况应该是验证码识别错了，暂时无解。
验证码每个账号每天貌似是不变的，你可以把这个验证码的图片发一下我看看能不能提高识别精度。

**Comment by LQY0606** [comment]
> > > 没这么夸张 而且说不定过两天再升级验证码之后我也放弃了……
> > 
> > 
> > 又失败了，验证码识别成功，提交打卡信息成功，最后却打卡失败。 ![Screenshot_20220908_005026_com microsoft emmx](https://user-images.githubusercontent.com/91514324/188935821-33d94d87-32ca-4973-a9ec-816d071da077.png)
> 
> 我这边没有问题。 你这边的情况应该是验证码识别错了，暂时无解。 验证码每个账号每天貌似是不变的，你可以把这个验证码的图片发一下我看看能不能提高识别精度。

![Screenshot_20220908_080711_com tencent mm](https://user-images.githubusercontent.com/91514324/189006081-73f3e7df-be75-4401-b7b6-f0fc6685c349.png)
验证码识别对了，不知道啥问题。

**Comment by SoodaMoe** [comment]
> > > > 没这么夸张 而且说不定过两天再升级验证码之后我也放弃了……
> > > 
> > > 
> > > 又失败了，验证码识别成功，提交打卡信息成功，最后却打卡失败。 ![Screenshot_20220908_005026_com microsoft emmx](https://user-images.githubusercontent.com/91514324/188935821-33d94d87-32ca-4973-a9ec-816d071da077.png)
> > 
> > 
> > 我这边没有问题。 你这边的情况应该是验证码识别错了，暂时无解。 验证码每个账号每天貌似是不变的，你可以把这个验证码的图片发一下我看看能不能提高识别精度。
> 
> ![Screenshot_20220908_080711_com tencent mm](https://user-images.githubusercontent.com/91514324/189006081-73f3e7df-be75-4401-b7b6-f0fc6685c349.png) 验证码识别对了，不知道啥问题。

可以等明天再试一下，还不行的话在就环境变量里加jksb_logger_level=DEBUG，这样会强制打卡，并且会显示更详细的日志信息，应该能推测是哪里出了问题

**Comment by LQY0606** [comment]
> > > > > 没这么夸张 而且说不定过两天再升级验证码之后我也放弃了……
> > > > 
> > > > 
> > > > 又失败了，验证码识别成功，提交打卡信息成功，最后却打卡失败。 ![Screenshot_20220908_005026_com microsoft emmx](https://user-images.githubusercontent.com/91514324/188935821-33d94d87-32ca-4973-a9ec-816d071da077.png)
> > > 
> > > 
> > > 我这边没有问题。 你这边的情况应该是验证码识别错了，暂时无解。 验证码每个账号每天貌似是不变的，你可以把这个验证码的图片发一下我看看能不能提高识别精度。
> > 
> > 
> > ![Screenshot_20220908_080711_com tencent mm](https://user-images.githubusercontent.com/91514324/189006081-73f3e7df-be75-4401-b7b6-f0fc6685c349.png) 验证码识别对了，不知道啥问题。
> 
> 可以等明天再试一下，还不行的话在就环境变量里加jksb_logger_level=DEBUG，这样会强制打卡，并且会显示更详细的日志信息，应该能推测是哪里出了问题

奇了怪了，没有验证码了还是失败
![Uploading Screenshot_20220910_002830_com.microsoft.emmx.png…]()

**Comment by LQY0606** [comment]
![Screenshot_20220910_002830_com microsoft emmx](https://user-images.githubusercontent.com/91514324/189398841-2a249a6a-b5b8-4e1d-9c11-53da452aa91c.png)

**Comment by SoodaMoe** [comment]
> ![Screenshot_20220910_002830_com microsoft emmx](https://user-images.githubusercontent.com/91514324/189398841-2a249a6a-b5b8-4e1d-9c11-53da452aa91c.png)

这种问题可能有两种原因：
1、如果日志报错，但是实际是打卡成功的话：
我这边判断打卡是否成功采用的方法是：每次打卡之后再登陆一次，查页面中对号的数量，如果有八个对号，就说明今天打卡成功了（因为那个页面会显示最近8天的打卡信息）（之所以采用这种方法是因为我原来碰到过明明提示打卡成功，但是回到打卡页面后却没有打上对钩的情况）
![屏幕截图 2022-09-10 154721](https://user-images.githubusercontent.com/31335213/189474355-93448708-6a43-4b0f-999b-200e79a83a2f.jpg)

那个对号图片的文件名是"2020ok.png"，如果因为什么原因导致count("2020ok.png")的结果不是8的话，就会出现明明打卡成功了，但是却返回打卡失败，这样我就需要你这边提供那个页面中对号那一部分的源代码来分析了。
![屏幕截图 2022-09-10 155314](https://user-images.githubusercontent.com/31335213/189474512-b83851fc-86e2-49ed-9e30-9fd9c533460c.jpg)


2、日志报错，实际也没打上卡：
可能是页面上某个隐藏参数我还没有找到，导致系统识别到是脚本，我已经更新代码，现在应该能显示出来打卡系统的报错信息，可以再尝试一下。

我这边好几个账号都能顺利打卡，如果还有什么问题我估计可能是一些疑难杂症，不太好处理，如果你用的是docker，可以试试用Github Action，或者直接下载源码，执行jksb.py文件，假如还不能解决，方便的话可以用其他联系方式详聊。
现在学校停用了验证码，如果嫌太麻烦也可以转用其他大佬的项目，他们的项目应该都可以用了。

**Comment by LQY0606** [comment]
> > ![Screenshot_20220910_002830_com microsoft emmx](https://user-images.githubusercontent.com/91514324/189398841-2a249a6a-b5b8-4e1d-9c11-53da452aa91c.png)
> 
> 这种问题可能有两种原因： 1、如果日志报错，但是实际是打卡成功的话： 我这边判断打卡是否成功采用的方法是：每次打卡之后再登陆一次，查页面中对号的数量，如果有八个对号，就说明今天打卡成功了（因为那个页面会显示最近8天的打卡信息）（之所以采用这种方法是因为我原来碰到过明明提示打卡成功，但是回到打卡页面后却没有打上对钩的情况） ![屏幕截图 2022-09-10 154721](https://user-images.githubusercontent.com/31335213/189474355-93448708-6a43-4b0f-999b-200e79a83a2f.jpg)
> 
> 那个对号图片的文件名是"2020ok.png"，如果因为什么原因导致count("2020ok.png")的结果不是8的话，就会出现明明打卡成功了，但是却返回打卡失败，这样我就需要你这边提供那个页面中对号那一部分的源代码来分析了。 ![屏幕截图 2022-09-10 155314](https://user-images.githubusercontent.com/31335213/189474512-b83851fc-86e2-49ed-9e30-9fd9c533460c.jpg)
> 
> 2、日志报错，实际也没打上卡： 可能是页面上某个隐藏参数我还没有找到，导致系统识别到是脚本，我已经更新代码，现在应该能显示出来打卡系统的报错信息，可以再尝试一下。
> 
> 我这边好几个账号都能顺利打卡，如果还有什么问题我估计可能是一些疑难杂症，不太好处理，如果你用的是docker，可以试试用Github Action，或者直接下载源码，执行jksb.py文件，假如还不能解决，方便的话可以用其他联系方式详聊。 现在学校停用了验证码，如果嫌太麻烦也可以转用其他大佬的项目，他们的项目应该都可以用了。

我用的docker运行的青龙打卡的，打卡确实没有成功，三个账号都失败。手动进去显示黄色的提示打卡未成功啥的，今晚再试一下吧。

**Comment by SoodaMoe** [comment]
> > > ![Screenshot_20220910_002830_com microsoft emmx](https://user-images.githubusercontent.com/91514324/189398841-2a249a6a-b5b8-4e1d-9c11-53da452aa91c.png)
> > 
> > 
> > 这种问题可能有两种原因： 1、如果日志报错，但是实际是打卡成功的话： 我这边判断打卡是否成功采用的方法是：每次打卡之后再登陆一次，查页面中对号的数量，如果有八个对号，就说明今天打卡成功了（因为那个页面会显示最近8天的打卡信息）（之所以采用这种方法是因为我原来碰到过明明提示打卡成功，但是回到打卡页面后却没有打上对钩的情况） ![屏幕截图 2022-09-10 154721](https://user-images.githubusercontent.com/31335213/189474355-93448708-6a43-4b0f-999b-200e79a83a2f.jpg)
> > 那个对号图片的文件名是"2020ok.png"，如果因为什么原因导致count("2020ok.png")的结果不是8的话，就会出现明明打卡成功了，但是却返回打卡失败，这样我就需要你这边提供那个页面中对号那一部分的源代码来分析了。 ![屏幕截图 2022-09-10 155314](https://user-images.githubusercontent.com/31335213/189474512-b83851fc-86e2-49ed-9e30-9fd9c533460c.jpg)
> > 2、日志报错，实际也没打上卡： 可能是页面上某个隐藏参数我还没有找到，导致系统识别到是脚本，我已经更新代码，现在应该能显示出来打卡系统的报错信息，可以再尝试一下。
> > 我这边好几个账号都能顺利打卡，如果还有什么问题我估计可能是一些疑难杂症，不太好处理，如果你用的是docker，可以试试用Github Action，或者直接下载源码，执行jksb.py文件，假如还不能解决，方便的话可以用其他联系方式详聊。 现在学校停用了验证码，如果嫌太麻烦也可以转用其他大佬的项目，他们的项目应该都可以用了。
> 
> 我用的docker运行的青龙打卡的，打卡确实没有成功，三个账号都失败。手动进去显示黄色的提示打卡未成功啥的，今晚再试一下吧。

我昨天试了一下这个青龙面板，我这边用青龙面板也能顺利打卡，这下真成疑难杂症了。。

**Comment by LQY0606** [comment]
> > > > ![Screenshot_20220910_002830_com microsoft emmx](https://user-images.githubusercontent.com/91514324/189398841-2a249a6a-b5b8-4e1d-9c11-53da452aa91c.png)
> > > 
> > > 
> > > 这种问题可能有两种原因： 1、如果日志报错，但是实际是打卡成功的话： 我这边判断打卡是否成功采用的方法是：每次打卡之后再登陆一次，查页面中对号的数量，如果有八个对号，就说明今天打卡成功了（因为那个页面会显示最近8天的打卡信息）（之所以采用这种方法是因为我原来碰到过明明提示打卡成功，但是回到打卡页面后却没有打上对钩的情况） ![屏幕截图 2022-09-10 154721](https://user-images.githubusercontent.com/31335213/189474355-93448708-6a43-4b0f-999b-200e79a83a2f.jpg)
> > > 那个对号图片的文件名是"2020ok.png"，如果因为什么原因导致count("2020ok.png")的结果不是8的话，就会出现明明打卡成功了，但是却返回打卡失败，这样我就需要你这边提供那个页面中对号那一部分的源代码来分析了。 ![屏幕截图 2022-09-10 155314](https://user-images.githubusercontent.com/31335213/189474512-b83851fc-86e2-49ed-9e30-9fd9c533460c.jpg)
> > > 2、日志报错，实际也没打上卡： 可能是页面上某个隐藏参数我还没有找到，导致系统识别到是脚本，我已经更新代码，现在应该能显示出来打卡系统的报错信息，可以再尝试一下。
> > > 我这边好几个账号都能顺利打卡，如果还有什么问题我估计可能是一些疑难杂症，不太好处理，如果你用的是docker，可以试试用Github Action，或者直接下载源码，执行jksb.py文件，假如还不能解决，方便的话可以用其他联系方式详聊。 现在学校停用了验证码，如果嫌太麻烦也可以转用其他大佬的项目，他们的项目应该都可以用了。
> > 
> > 
> > 我用的docker运行的青龙打卡的，打卡确实没有成功，三个账号都失败。手动进去显示黄色的提示打卡未成功啥的，今晚再试一下吧。
> 
> 我昨天试了一下这个青龙面板，我这边用青龙面板也能顺利打卡，这下真成疑难杂症了。。

失败了但又没完全失败

![捕获(1)](https://user-images.githubusercontent.com/91514324/189513074-3742782a-1ff9-4dfc-a37c-d7c3a996ef12.PNG)


手动进打卡页面显示这个
![Screenshot_20220911_002837_com tencent mm](https://user-images.githubusercontent.com/91514324/189513090-5f878ffa-446a-491d-8f69-829c75707584.png)


但我手动打卡后，显示打卡时间却是自动打卡失败的时间
![Screenshot_20220911_125424_com tencent mm](https://user-images.githubusercontent.com/91514324/189513130-0b7effc7-6e30-4157-b411-687a787a89b0.png)

**Comment by SoodaMoe** [comment]
> > > > > ![Screenshot_20220910_002830_com microsoft emmx](https://user-images.githubusercontent.com/91514324/189398841-2a249a6a-b5b8-4e1d-9c11-53da452aa91c.png)
> > > > 
> > > > 
> > > > 这种问题可能有两种原因： 1、如果日志报错，但是实际是打卡成功的话： 我这边判断打卡是否成功采用的方法是：每次打卡之后再登陆一次，查页面中对号的数量，如果有八个对号，就说明今天打卡成功了（因为那个页面会显示最近8天的打卡信息）（之所以采用这种方法是因为我原来碰到过明明提示打卡成功，但是回到打卡页面后却没有打上对钩的情况） ![屏幕截图 2022-09-10 154721](https://user-images.githubusercontent.com/31335213/189474355-93448708-6a43-4b0f-999b-200e79a83a2f.jpg)
> > > > 那个对号图片的文件名是"2020ok.png"，如果因为什么原因导致count("2020ok.png")的结果不是8的话，就会出现明明打卡成功了，但是却返回打卡失败，这样我就需要你这边提供那个页面中对号那一部分的源代码来分析了。 ![屏幕截图 2022-09-10 155314](https://user-images.githubusercontent.com/31335213/189474512-b83851fc-86e2-49ed-9e30-9fd9c533460c.jpg)
> > > > 2、日志报错，实际也没打上卡： 可能是页面上某个隐藏参数我还没有找到，导致系统识别到是脚本，我已经更新代码，现在应该能显示出来打卡系统的报错信息，可以再尝试一下。
> > > > 我这边好几个账号都能顺利打卡，如果还有什么问题我估计可能是一些疑难杂症，不太好处理，如果你用的是docker，可以试试用Github Action，或者直接下载源码，执行jksb.py文件，假如还不能解决，方便的话可以用其他联系方式详聊。 现在学校停用了验证码，如果嫌太麻烦也可以转用其他大佬的项目，他们的项目应该都可以用了。
> > > 
> > > 
> > > 我用的docker运行的青龙打卡的，打卡确实没有成功，三个账号都失败。手动进去显示黄色的提示打卡未成功啥的，今晚再试一下吧。
> > 
> > 
> > 我昨天试了一下这个青龙面板，我这边用青龙面板也能顺利打卡，这下真成疑难杂症了。。
> 
> 失败了但又没完全失败
> 
> ![捕获(1)](https://user-images.githubusercontent.com/91514324/189513074-3742782a-1ff9-4dfc-a37c-d7c3a996ef12.PNG)
> 
> 手动进打卡页面显示这个 ![Screenshot_20220911_002837_com tencent mm](https://user-images.githubusercontent.com/91514324/189513090-5f878ffa-446a-491d-8f69-829c75707584.png)
> 
> 但我手动打卡后，显示打卡时间却是自动打卡失败的时间 ![Screenshot_20220911_125424_com tencent mm](https://user-images.githubusercontent.com/91514324/189513130-0b7effc7-6e30-4157-b411-687a787a89b0.png)

这样的话可能就需要你在jksb.py的第126行前加print(response_data.data.decode())来查看打卡之后页面返回的数据了，保险起见，utils.py的第51行前也加一句print(r.data.decode())吧，有这两个页面返回的数据应该就能定位原因了。
