### ISSUE TITLE
邮箱发送无法使用...

### ISSUE THREAD

**Issue by 233333LSSSSSSSS** [Yann-zhou/zzu_auto_jksb#3]
{temp.qq.cpm，邮箱，密码，邮箱}这样的格式       还是   temp.qq.com，邮箱，密码，邮箱    这样的格式？？
密码是邮箱授权码还是QQ密码？？

**Comment by LQY0606** [comment]
教程写的很明白了
![Screenshot_20220910_004845_com microsoft emmx](https://user-images.githubusercontent.com/91514324/189401001-03b1fdb5-ef11-4df6-8b15-26449e01a777.png)
密码是授权码

**Comment by SoodaMoe** [comment]
> {temp.qq.cpm，邮箱，密码，邮箱}这样的格式 还是 temp.qq.com，邮箱，密码，邮箱 这样的格式？？ 密码是邮箱授权码还是QQ密码？？

按照图中这样的格式填写，需要有大括号，密码是授权码，不是QQ密码。
我已经试过了，QQ邮箱可以正常接收邮件。
![QQ截图20220910160716](https://user-images.githubusercontent.com/31335213/189474911-d720226b-c250-40c9-8180-849a05d2b3e1.jpg)
