### ISSUE TITLE
docker中的jksb_timer怎么设置

### ISSUE THREAD

**Issue by QTiiiiiiiiiiii** [Yann-zhou/zzu_auto_jksb#4]

**Comment by SoodaMoe** [comment]
> _No description provided._

教程里忘了写了，抱歉，jksb_timer按照如下格式填写：
[[第1个打卡时间的小时,第1个打卡时间的分钟,第1个打卡时间随机偏移量],[第2个打卡时间的小时,第2个打卡时间的分钟,第2个打卡时间随机偏移量],,......[第n个打卡时间的小时,第n个打卡时间的分钟,第n个打卡时间随机偏移量]]
填写例子如下：
[[0,5,300],[1,5,300],[8,5,300]]
按照这个格式填写的话，会在每天0:05,1:05,8:05这三个时间自动打卡，并且会在300秒时间内取一个随机时间防止脚本被打卡系统察觉
