### ISSUE TITLE
打卡失败报错

### ISSUE THREAD

**Issue by Kiddo019** [Yann-zhou/zzu_auto_jksb#6]
2022-11-26 18:22:04,217- jksb_tools-[INFO]-已使用***模式发送消息“程序运行异常！错误
信息: 'NoneType' object has no attribute 'group'"

**Comment by SoodaMoe** [comment]
我这边几个人都失败了，正在排查原因

**Comment by SoodaMoe** [comment]
已经更新最新的参数字段，今晚可以再试一下效果。

**Comment by Kiddo019** [comment]
> 已经更新最新的参数字段，今晚可以再试一下效果。

好像还是同样的报错

**Comment by SoodaMoe** [comment]
> > 已经更新最新的参数字段，今晚可以再试一下效果。
> 
> 好像还是同样的报错

昨天又更新了一版，现在我这边已经可以成功打上卡了，麻烦再重新fork或pull一下试试

**Comment by Nuomanzzz** [comment]
终于成功了哥

**Comment by Kiddo019** [comment]
成功了老哥👍
